name: pulse_pro
description: "A new Flutter project."
publish_to: 'none'

version: 99.99.99+99

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  #firebase
  firebase_core: ^2.24.2
  firebase_app_check: ^0.2.1+8
  firebase_auth: ^4.16.0
  firebase_analytics: ^10.8.0
  firebase_storage: ^11.6.0
  cloud_firestore: ^4.17.2
  cloud_functions: ^4.6.0
  firebase_messaging: ^14.7.10
  firebase_remote_config: ^4.3.8

  go_router: ^14.0.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_lints: ^3.0.0
  test: ^1.24.9
  bloc_test: ^9.1.7
  build_runner: ^2.4.9
  mockito: ^5.4.4
  network_image_mock: ^2.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/login_background.jpg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700