name: Flutter Build, Release And Deploy

on:
  push:
    tags:
      - 'v*'

jobs:

  version:
    name: Create version number from tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Extract version from tag
        id: tagversion
        run: echo "VERSION=${GITHUB_REF_NAME:1}" >> $GITHUB_ENV
      - name: Create version.txt with tag version
        run: echo $VERSION > version.txt
      - name: Upload version.txt
        uses: actions/upload-artifact@v4
        with:
          name: tagversion
          path: version.txt

  flutter_test:
    name: Run flutter test and analyze
    needs: [version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print github context
        run: echo "Run number: ${{ github.run_number }}"
      - name: Get version.txt
        uses: actions/download-artifact@v4
        with:
          name: tagversion
      - name: Read version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: version.txt
      - name: Update version in YAML
        run: sed -i "s/99.99.99+99/\${{ steps.version.outputs.content }}+\${{ github.run_number }}/g" pubspec.yaml
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "18.x"
      - name: Setup Flutter    
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.6"
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test

  build_appbundle:
    name: Generate appbundle files
    needs: [flutter_test]
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Setup Java environment in order to build the Android app.
      - uses: actions/checkout@v3
      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'upload-keystore.jks'
          encodedString: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties    
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "11.x"
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.6"
          channel: "stable"
      - name: Install dependencies
        run: flutter pub get
      - name: Build appbundle 
        run: flutter build appbundle --flavor prod
      - name: Upload Android Release
        uses: actions/upload-artifact@v4
        with:
          name: android-release
          path: build/app/outputs/bundle/prodRelease/app-prod-release.aab

  deploy:
    name: Deploy Android Build
    needs: [build_appbundle]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get the tag name
      id: get_tag
      run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    - name: Get Android Build from artifacts
      uses: actions/download-artifact@v4
      with:
        name: android-release
    - name: Release Build to internal track
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.PLAYSTORE_ACCOUNT_KEY }}
        packageName: ai.pulsepro.app
        releaseFiles: app-prod-release.aab
        track: production
        status: completed
        releaseName: $TAG_NAME